name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_USER: postgres
          POSTGRES_DB: newsletter
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Migrate database
        run: |
          sudo apt-get install libpq-dev -y
          cargo install --version=^0.6 sqlx-cli --no-default-features --features rustls,postgres
          sqlx database create
          sqlx migrate run
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
    env:
      DATABASE_URL: postgres://postgres:password@localhost:5432/newsletter

  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Migrate database
        run: |
          sudo apt-get install libpq-dev -y
          cargo install --version=^0.6 sqlx-cli --no-default-features --features rustls,postgres
          sqlx database create
          sqlx migrate run
      - name: Run Clippy
        run: cargo clippy --all-features -- -D warnings

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Format
        run: cargo fmt -- --check
